# Generated by Django 4.1.13 on 2026-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_producttransaction_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='deposit_category',
            field=models.CharField(blank=True, editable=False, max_length=125, null=True),
        ),
    ]
