# Generated by Django 4.1.13 on 2026-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_producttransaction_deposit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_due',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(default='PAID', editable=False, max_length=16),
        ),
    ]
