# Generated by Django 4.1.13 on 2026-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_category',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
