# Generated by Django 4.1.13 on 2026-04-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_deposit_deposit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deposit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.deposit'),
        ),
    ]
